#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightBlue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = "dotnet"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "#6a0dad"
    template = " 󰪮 {{ .Full }} "

  [[blocks.segments]]
    type = "go"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#00add8"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "ruby"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#7a1045"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "node"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#3c873a"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "angular"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "#a6120d"
    template = "{{ if .Full }}  {{ .Full }} {{ end }}"

  [[blocks.segments]]
    type = "react"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "blue"
    template = "{{ if .Full }}  {{ .Full }} {{ end }}"

  [[blocks.segments]]
    type = "java"
    style = "powerline"
    powerline_symbol = ""
    foreground = "blue"
    background = "#ec833f"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = 'terraform'
    style = 'powerline'
    powerline_symbol = ""
    foreground = "white"
    background = "magenta"
    template = " 󱁢 {{ .WorkspaceName }} "

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
